### ISSUE TITLE
Suggestion #1: Image sliders

### ISSUE THREAD

**Issue by CircuitRCAY** [AlexFlipnote/ModestaCSS#1]
ModestaCSS could have image sliders for portfolios etc.

**Comment by AlexFlipnote** [comment]
Will look into it.

**Comment by CircuitRCAY** [comment]
I see.

**Comment by AlexFlipnote** [comment]
I won't cover too much JS in this framework as it's called Modesta**CSS**
Yes I do have JS for some stuff but that's just needed for few things.
