### ISSUE TITLE
Move from ruby to dart or libsass?

### ISSUE THREAD

**Issue by kotx** [AlexFlipnote/ModestaCSS#14]
```Ruby Sass was the original implementation of Sass, but it's since been deprecated. It's currently in a sunset maintenance period, and it will be officially unmaintained one year after the release of Dart Sass 1.0.0. Ruby Sass users should migrate to another implementation.```

**Comment by AlexFlipnote** [comment]
Was considering to switch over, but I want to wait for every thing like my linter to switch over too before I do it.
