### ISSUE TITLE
<button> with .btn collides with button styles

### ISSUE THREAD

**Issue by 7coil** [AlexFlipnote/ModestaCSS#21]
When `<button class="btn"></button>` is used, the box shadow of the `<button>` makes the `btn` look weird

![image](https://user-images.githubusercontent.com/13886925/57002471-8bca7800-6bb7-11e9-9024-4d822afebc8f.png)

This can be bodged to be fixed by doing a `box-shadow: unset !important`

Unticking box-shadow simulation

![image](https://user-images.githubusercontent.com/13886925/57002518-e8c62e00-6bb7-11e9-9b9b-72eb638c6b76.png)

_the button looks like a normal button_

---

_imo, ModestaCSS shouldn't use any element selectors, as i have to override them later_

**Comment by AlexFlipnote** [comment]
This has been resolved now at 9b67dbf
