### ISSUE TITLE
New color suggestion

### ISSUE THREAD

**Issue by Soheab** [AlexFlipnote/ModestaCSS#22]
The official discord color's would nice from here: https://discordapp.com/branding
i tried to make it easier for you by doing this.. sorry if this is not how it works, i have no idea lol:
i also check here: https://modesta.alexflipnote.dev/css/colours.min.css if the color doesn't already exist.

# Colors:

Blurple: (#7289DA) already added and named discord
-------------
Full white: #7289DA

.Full-white{background-color:#FFFFFF}.Full-white-text{color:#FFFFFF}.Full-white-dropshadow{background-color:#FFFFFF;filter:drop-shadow(5px 5px 0 rgba(255, 255, 255,0.6))}
-------------
Greyple: #99AAB5

.Greyple{background-color:#99AAB5}.Greyple-text{color:#99AAB5}.Greyple-dropshadow{background-color:#99AAB5;filter:drop-shadow(5px 5px 0 rgba(153, 170, 181,0.6))}
-------------
Dark, but not black: #2C2F33

.dark-not-black{background-color:#2C2F33}.dark-not-black-text{color:#2C2F33}.dark-not-black-dropshadow{background-color:#2C2F33;filter:drop-shadow(5px 5px 0 rgba(44, 47, 51,0.6))}
-------------
Not quite black: #23272A

.not-black{background-color:#23272A}.not-black-text{color:#23272A}.not-black-dropshadow{background-color:#23272A;filter:drop-shadow(5px 5px 0 rgba(35, 39, 42,0.6))}

**Comment by AlexFlipnote** [comment]
Sure I can add a few more colours.

**Comment by AlexFlipnote** [comment]
Done
