### ISSUE TITLE
<!DOCTYPE html>

### ISSUE THREAD

**Issue by xhyrom** [AlexFlipnote/ModestaCSS#31]
Could you publish a version that will work for DOCTYPE html?

**Comment by AlexFlipnote** [comment]
I'll look into it

**Comment by xhyrom** [comment]
Thanks 
i try to make html without erroru: D (https://validator.w3.org/nu/?doc=https://hyro.tech)

**Comment by AlexFlipnote** [comment]
I've never cared enough about it because it's not required in HTML5, but might as well make Modesta support HTML4 :P

**Comment by xHyroM** [comment]
Yes, but what I have read may happen that browsers will stop supporting HTML4, so I would like to ask if you would do this for HTML5 @AlexFlipnote

**Comment by xHyroM** [comment]
This means that the browser will automatically put it there as if DOCTYPE html. And there is a problem that then the fullscreen class does not work and it bugs.

**Comment by jzeuzs** [comment]
I also experienced this bug.

**Comment by AlexFlipnote** [comment]
This will be fixed in v3 release
